### ISSUE TITLE
Using NGSIM dataset

### ISSUE THREAD

**Issue by imanshahmari** [THU-changc17/MetaScenario#1]
I am using NGSIM dataset. By the time I am using the dataset they have added more than I-80 data to the dataset so I extracted only I-80 location data from the csv and i am trying to run the code. What I dont understand is the variable table which is set to _3 in NGSIM_I80_InsertTrafficParticipant.py and then its set to _7 in Alter_ForeignKey.py and then its varying from 1 to 4 in NGSIM_Data_Annotator_v2.py. What is this variable doing and why is it hardcoded?

**Comment by THU-changc17** [comment]
Thanks for your comment.

Each time you insert an independent data file, you need to set its tableID in the database. Thus the database tables about traffic participants are named Traffic_timing_state_(tableID) and Traffic_participant_property_(tableID). Considering that researchers may not import all the data files, we do not set the default loop here.  In contrast, when we annotate the data, the scenarios for each table in the database are all needed to be labeled, so the default loop is set in the sample code.

Specific to the meaning of the variables, "_3" is the third file of NGSIM I-80 data, and the Annotator tools contain the loop numbers for NGSIM dataset.
As the Alter_ForeignKey.py is common for all datasets, the example in the code is shown as Interaction Intersection Dataset. "_7" refers to the 7th table of vehicle tracking files. 

In fact, it will be more convenient in the form of arguments. At this stage, users need to slightly modify the IDs and data file names to adapt the code. We will also update and add new codes in the near future.
